### ISSUE TITLE
How to install signed plugins in AWS managed grafana

### ISSUE THREAD

**Issue by saumilsdk** [aws/amazon-managed-grafana-roadmap#36] opened 2023-02-15 13:25 UTC
How to install signed plugins in AWS managed grafana

**Comment by heldersepu** [comment] 2023-04-06 12:14
Looks like a duplicate of https://github.com/aws/amazon-managed-grafana-roadmap/issues/15

**Closed as completed** 2023-10-03 20:16 UTC

**Comment by VermaPriyanka** [comment] 2023-11-21 13:47
Refer to this announcement: https://github.com/aws/amazon-managed-grafana-roadmap/discussions/67
